### ISSUE TITLE
Mod sorting cycle in1.50 error

### ISSUE THREAD

**Issue by iTraumatik** [Tonius/SimplyJetpacks#103]
[11:04:17] [Client thread/ERROR] [FML/]: Likely cycle is in : [FMLMod:simplyjetpacks{1.5.0}, Dummy Container (AfterAll) @416516744, Dummy Container (After) @1654100003, FMLMod:RArm{1.7.10-1.1-22}]
[11:04:17] [Client thread/ERROR] [FML/]: A dependency cycle was detected in the input mod set so an ordering cannot be determined
[11:04:17] [Client thread/ERROR] [FML/]: The first mod in the cycle is FMLMod:RArm{1.7.10-1.1-22}
[11:04:17] [Client thread/ERROR] [FML/]: The mod cycle involves
[11:04:17] [Client thread/ERROR] [FML/]: FMLMod:simplyjetpacks{1.5.0} : before: [], after: [Forge@[10.13.2.1291,), ThermalExpansion, RedstoneArsenal, RArm, EnderIO@[1.7.10-2.1.3.243,), BuildCraft|Core@[6.4.15,7.0.0),[7.0.4,)]
[11:04:17] [Client thread/ERROR] [FML/]: Dummy Container (AfterAll) @416516744 : before: [], after: []
[11:04:17] [Client thread/ERROR] [FML/]: Dummy Container (After) @1654100003 : before: [], after: []
[11:04:17] [Client thread/ERROR] [FML/]: FMLMod:RArm{1.7.10-1.1-22} : before: [], after: [RedstoneArsenal, ttCore, ThermalFoundation, simplyjetpacks]
[11:04:17] [Client thread/ERROR] [FML/]: The full error
cpw.mods.fml.common.toposort.ModSortingException: There was a cycle detected in the input graph, sorting is not possible
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:190) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.explore(TopologicalSort.java:199) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.TopologicalSort.topologicalSort(TopologicalSort.java:145) ~[TopologicalSort.class:?]
	at cpw.mods.fml.common.toposort.ModSorter.sort(ModSorter.java:133) ~[ModSorter.class:?]
	at cpw.mods.fml.common.Loader.sortModList(Loader.java:270) [Loader.class:?]
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:491) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:206) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[11:04:17] [Client thread/DEBUG] [FML/]: Mod sorting data

Modpack was fine before replacing SJP 1.41 with  SJP 1.50.   I have all newest COFH mods (not dev versions).

**Comment by Tonius** [comment]
Try updating Redstone Armory? Looks like some leftover code in an older version of RArm makes it want to load after SJ, while SJ 1.5.0 wants to load after RArm.

**Comment by iTraumatik** [comment]
Works with RA.32 newest.  Thanks.   Looks like i will have to not rely on notenoughmods website to be truly automatic and up to date.  Their version is 15 days old.  Thanks again.
