### ISSUE TITLE
Trying to craft tier 3 ender io jetpack crashes the game

### ISSUE THREAD

**Issue by Kazzamkablam** [Tonius/SimplyJetpacks#104]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 5/23/15 9:50 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at tonius.simplyjetpacks.crafting.UpgradingRecipe.func_77572_b(UpgradingRecipe.java:47)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:325)
	at net.minecraft.inventory.ContainerWorkbench.func_75130_a(SourceFile:53)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Update, it seems to happen with all jetpack crafting recipes.

**Comment by nabijaczleweli** [comment]
`slotStack.getItem()` might be `null`, and @Tonius doesn't check for that. Only reasonable solution to me. (only briefly looked through it)

**Comment by Tonius** [comment]
I see what's happening here:
https://github.com/Tonius/SimplyJetpacks/blob/master/src/main/java/tonius/simplyjetpacks/crafting/UpgradingRecipe.java#L47

`ModItems.enderiumUpgrade` is `null` whenever Redstone Armory is not installed.

I'll release a fix for this later today.

**Comment by nabijaczleweli** [comment]
So that WAS what I originally thought! But then, I realized (erroneously), that no `ModItem` could possibly be `null`.
