### ISSUE TITLE
Fatal Error after server restarts

### ISSUE THREAD

**Issue by Allalous** [Tonius/SimplyJetpacks#115]
My friends and I play on a custom modpack with your mod (it's on cursed called The RyRyPatPatPackPack) and we haven't have any problems until recently. Whenever our server does it's auto restarts, everyone gets this "A fatal error has occurred" afterwards and we either have to manually restart the server before people can log back in or people have to reinstall the modpack. The last thing any of our console log says when we get this error is this:

[Netty Client IO #5/INFO] [simplyjetpacks]: Loading configuration files

Then it just stops. No one has received a crash report from this so I can't show anything else. Next time it happens I'll try to show more of what it says.

**Comment by Allalous** [comment]
One of my friends got it right after I posted that other. Now the fluid thing is never the same, some people get iron others will get like cobalt or mithril, but everyone has the same last line of the simply jetpacks.

[09:31:46] [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel FORGE
java.lang.IllegalArgumentException: value already present: cobalt
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:238) ~[guava-17.0.jar:?]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:215) ~[guava-17.0.jar:?]
	at net.minecraftforge.fluids.FluidRegistry.loadFluidDefaults(FluidRegistry.java:117) ~[FluidRegistry.class:?]
	at net.minecraftforge.fluids.FluidRegistry.initFluidIDs(FluidRegistry.java:82) ~[FluidRegistry.class:?]
	at net.minecraftforge.common.network.FluidIdRegistryMessageHandler.channelRead0(FluidIdRegistryMessageHandler.java:15) ~[FluidIdRegistryMessageHandler.class:?]
	at net.minecraftforge.common.network.FluidIdRegistryMessageHandler.channelRead0(FluidIdRegistryMessageHandler.java:11) ~[FluidIdRegistryMessageHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
[09:31:46] [Netty Client IO #1/INFO] [simplyjetpacks]: Loading configuration files

**Comment by Alaberti** [comment]
What version of forge are you running on the client/server? You have a lot of mods that require at least forge 1355 due to the changes in the fluid registry. I'm not really sure this is a simply jetpack issue.

**Comment by Tonius** [comment]
Closing for inactivity. If this is still an issue for you, please open another issue.
