### ISSUE TITLE
broken ore dictionary registration with name ingotDarkSoularium

### ISSUE THREAD

**Issue by piotrb** [Tonius/SimplyJetpacks#122]
This is on version 1.5.2

```
[19:46:07] [Client thread/WARN] [FML]: ****************************************
[19:46:07] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name ingotDarkSoularium has occurred. It adds an item (type: class tonius.simplyjetpacks.item.ItemMeta) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod Simply Jetpacks report it to them!
[19:46:07] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(OreDictionary.java:507)
[19:46:07] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(OreDictionary.java:474)
[19:46:07] [Client thread/WARN] [FML]: *  at tonius.simplyjetpacks.item.ItemMeta.addMetaItem(ItemMeta.java:56)
[19:46:07] [Client thread/WARN] [FML]: *  at tonius.simplyjetpacks.setup.ModItems.constructItems(ModItems.java:178)
[19:46:07] [Client thread/WARN] [FML]: *  at tonius.simplyjetpacks.setup.ModItems.preInit(ModItems.java:48)
[19:46:07] [Client thread/WARN] [FML]: *  at tonius.simplyjetpacks.SimplyJetpacks.preInit(SimplyJetpacks.java:49)...
[19:46:07] [Client thread/WARN] [FML]: ****************************************
```

**Comment by usafphoenix** [comment]
Getting this, as well as errors pointing to ElectrumFlux of types ingot, nugget, and gem.
