### ISSUE TITLE
Causing Minecraft to Crash (NPE:Rendering Item : tonius.simplyjetpacks.item.ItemPack$ItemJetpack@2b05e15b)

### ISSUE THREAD

**Issue by bookking3000** [Tonius/SimplyJetpacks#139]
`net.minecraft.util.ReportedException: Rendering item
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:604) ~[bny.class:?]
	at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955) ~[bbv.class:?]
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206) ~[GuiIngameForge.class:?]
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141) ~[GuiIngameForge.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1365) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.renderer.entity.RenderItem.func_94149_a(RenderItem.java:732) ~[bny.class:?]
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:498) ~[bny.class:?]
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565) ~[bny.class:?]
	... 13 more
[19:35:47] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----

Time: 4/11/17 7:35 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.minecraft.client.renderer.entity.RenderItem.func_94149_a(RenderItem.java:732)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:498)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1365)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_94149_a(RenderItem.java:732)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:498)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)

-- Item being rendered --
Details:
	Item Type: tonius.simplyjetpacks.item.ItemPack$ItemJetpack@2b05e15b
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.gui.GuiIngame.func_73832_a(GuiIngame.java:955)
	at net.minecraftforge.client.GuiIngameForge.renderHotbar(GuiIngameForge.java:206)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:141)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1365)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['bookking3000'/10928735, l='MpServer', x=-240.06, y=69.62, z=316.01]]
	Chunk stats: MultiplayerChunkCache: 45, 45
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-101,70,228), Chunk: (at 11,4,4 in -7,14; contains blocks -112,0,224 to -97,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 56461693 game time, 40885370 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 71 total`

**Comment by planetguy32** [comment]
Did you encounter this after updating SimplyJetpacks? I updated from a quite old version to the latest, then I started getting errors like this.

**Comment by bookking3000** [comment]
I didn't uptade it, since i was using the FTB Infinity Evolved Modpack(1.7.10), which uses SimplyJetpack`s 1.5.3. I think 1.5.3 is the latest Version available, i didn`t test it on lower Versions.
